# Generated by Django 2.2 on 2019-04-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('birth', models.DateField()),
                ('company', models.CharField(choices=[('soft_serve', 'SoftServe'), ('daxx_bv', 'Daxx BV'), ('levi9_ukraine', 'Levi9 Ukraine'), ('evoplay', 'Evoplay'), ('apriorit', 'Apriorit')], max_length=150)),
                ('position', models.CharField(choices=[('developer', 'Developer'), ('devops', 'DevOps'), ('manager', 'Manager')], max_length=15)),
                ('language', models.CharField(choices=[('ruby', 'Ruby'), ('python', 'Python'), ('java', 'Java'), ('asm', 'Assembler'), ('cpp', 'C++')], default=('ruby', 'Ruby'), max_length=10)),
            ],
        ),
    ]
