# Generated by Django 2.2 on 2019-04-15 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='human',
            options={'verbose_name': 'Человечек', 'verbose_name_plural': 'Человечеки'},
        ),
    ]
