# Generated by Django 2.2 on 2019-04-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdatabase', '0002_auto_20190415_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='company',
            field=models.CharField(choices=[('soft_serve', 'SoftServe'), ('daxx_bv', 'Daxx BV'), ('levi9_ukraine', 'Levi9 Ukraine'), ('Evoplay', 'evoplay'), ('apriorit', 'Apriorit')], max_length=150),
        ),
    ]
