# Generated by Django 2.2 on 2019-04-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdatabase', '0003_auto_20190416_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='company',
            field=models.CharField(choices=[('soft_serve', 'SoftServe'), ('Daxx BV', 'daxx_bv'), ('levi9_ukraine', 'Levi9 Ukraine'), ('evoplay', 'Evoplay'), ('apriorit', 'Apriorit')], max_length=150),
        ),
    ]
