# Generated by Django 2.2 on 2019-04-10 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationmodels', '0002_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Назва')),
                ('description', models.TextField(max_length=1000, verbose_name='Опис')),
                ('genre', models.CharField(choices=[('detective', 'Детектив'), ('thriller', 'Триллер'), ('drama', 'Драма'), ('roman', 'Роман'), ('comics', 'Комiкс'), ('prose', 'Проза')], max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicationmodels.Author')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
