# Generated by Django 2.2 on 2019-04-10 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationmodels', '0004_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='applicationmodels.Place')),
                ('name', models.TextField(max_length=50, verbose_name='Назва')),
                ('home_delivery', models.BooleanField(verbose_name=False)),
                ('noctidial', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
