# Generated by Django 2.2 on 2019-04-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationmodels', '0005_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='name',
        ),
    ]
