# Generated by Django 2.2 on 2019-04-10 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationmodels', '0006_remove_restaurant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name="Iм'я")),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicationmodels.Restaurant')),
            ],
        ),
    ]
