# Generated by Django 2.2 on 2019-04-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationmodels', '0008_article_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='big_int_field',
            field=models.BigIntegerField(default=10),
        ),
    ]
